---
version: 2
builds:
  -  # First Build
    env:
      - CGO_ENABLED=0
    main: ./cmd/fleeting-plugin-openstack
    ldflags: >-
      -s -w
      -X github.com/myplixa/openstack-fleeting-plugin.Version={{.Version}}
      -X github.com/myplixa/openstack-fleeting-plugin.Revision={{.FullCommit}}
      -X github.com/myplixa/openstack-fleeting-plugin.Branch={{.Branch}}
      -X github.com/myplixa/openstack-fleeting-plugin.BuildUser=goreleaser@github-actions
      -X github.com/myplixa/openstack-fleeting-plugin.BuildDate={{time "20060102-15:04:05"}}

    binary: "{{ .ProjectName }}"
    targets:
      - linux_386
      - linux_amd64
      - linux_arm_7
      - linux_arm64

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512

archives:
  - id: binary
    formats: binary
